SHOW DATABASES;
CREATE DATABASE Ninewells_Hospital;
USE Ninewells_Hospital;
CREATE USER  IF NOT EXISTS Admin IDENTIFIED BY 'ADMINPWD';
CREATE USER IF NOT EXISTS Doctor IDENTIFIED BY 'DRPWD';
CREATE USER IF NOT EXISTS Patients IDENTIFIED BY 'PTSPWD';
CREATE USER IF NOT EXISTS Laboratory_Staff IDENTIFIED BY 'LabStaffPWD';

SELECT USER FROM  mysql.user;

GRANT ALL PRIVILEGES ON *.* TO Admin WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON *.* TO Doctor;

GRANT READ ON *.* TO Patients;

GRANT ALL PRIVILEGES ON *.* TO Admin;

REVOKE CREATE USER ON Ninewells_Hospital.*from 'Laboratary_Staff'@'localhost';